### ISSUE TITLE
Uso do pacote

### ISSUE THREAD

**Issue by lucianoreis** [fgsl/microserviceframework#7]
Existe algum artigo explicando como usar a autenticação?
Só olhando as classes eu não consegui sacar como usar no meu projeto.

**Comment by fgsl** [comment]
A classe de autenticação é uma implementação de AdapterInterface do componente Laminas Authentication.

Experimente refazer os exemplos da documentação com essa classe, para começar.

https://docs.laminas.dev/laminas-authentication/intro/
